version: 2
jobs:
  build:
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    environment:
      # Files that we use to determine whether to build.
      DOCKER_BUILD_PATTERN: '^\(docker\|.circleci\)/'

    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.6

      - run:
          name: "Build Docker Image"
          command: |
            if ! git show --name-only --format='' HEAD | grep -q "$DOCKER_BUILD_PATTERN"; then
              exit
            fi
            if [ -n "$CIRCLE_TAG" ]; then
              tag="$CIRCLE_TAG"
            elif [ "$CIRCLE_BRANCH" = "main" ]; then
              tag=latest
            else
              tag="$CIRCLE_BRANCH"
            fi
            docker build -t docker.io/martinthomson/i-d-template-action:"$tag" docker/action
            docker build -t docker.io/martinthomson/i-d-template:"$tag" \
              --build-arg REGISTRY=docker.io --build-arg VERSION="$tag" docker/circleci

      - run:
          name: "Run Tests"
          command: |
            if [ -n "$CIRCLE_TAG" ]; then
              exit
            fi
            if ! git show --name-only --format='' HEAD | grep -q "$DOCKER_BUILD_PATTERN"; then
              tag=latest
            elif [ "$CIRCLE_BRANCH" = "main" ]; then
              tag=latest
            else
              tag="$CIRCLE_BRANCH"
            fi
            set -x
            cleanup() { set +e; docker cp test:/tmp/artifacts /tmp/artifacts; docker rm -f test; }
            trap cleanup EXIT
            docker run -d --name test \
              docker.io/martinthomson/i-d-template:"$tag" sleep 300
            docker cp . test:/test
            docker exec -u 0 test chown -R idci:idci /test
            docker exec -u 0 test apk add black
            docker exec -w /test test black --check .
            docker exec -u 0 test pip3 install --break-system-packages behave
            docker exec test mkdir /tmp/artifacts
            docker exec -w /test test behave --junit --junit-directory /tmp/artifacts /test/tests

      - run:
          name: "Push Docker Image"
          command: |
            if ! git show --name-only --format='' HEAD | grep -q "$DOCKER_BUILD_PATTERN"; then
              exit
            fi
            if [ -n "$CIRCLE_TAG" ]; then
              tag="$CIRCLE_TAG"
            elif [ "$CIRCLE_BRANCH" = "main" ]; then
              tag=latest
            else
              exit
            fi
            if [ -n "$DOCKER_PASSWORD" ]; then
              echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
              docker push docker.io/martinthomson/i-d-template:"$tag"
            fi

      - store_artifacts:
          path: /tmp/artifacts

      - store_test_results:
          path: /tmp/artifacts


workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*?/
